variables:
  # Various retry settings for Gitlab runners
  RESTORE_CACHE_ATTEMPTS: 2

stages:
  - build

# =======================================================================
# Build and deploy the images used for CI
# Read the instructions here: http://dtdg.co/dd-analytics-ci-image-workflow
.build-ci-image: &build-ci-image
  stage: build
  tags: ["runner:docker"]
  image: $CI_DOCKER_IMAGE
  script:
    - TAG="$IMAGE_TAG_PREFIX-$CI_COMMIT_SHA"
    - docker build --file $DOCKERFILE --tag 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/opentelemetry-collector-contrib:$TAG .
    - docker push 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/opentelemetry-collector-contrib:$TAG

build-ci-image-main:
  <<: *build-ci-image
  variables:
    DOCKERFILE: ci/Dockerfile
    IMAGE_TAG_PREFIX: votelcolcontrib

