variables:
  CI_PROJECT_NAME: "opentelemetry-collector-contrib"
  BUILD_STABLE_REGISTRY: "486234852809.dkr.ecr.us-east-1.amazonaws.com"
  CI_IMAGE: registry.ddbuild.io/ci/opentelemetry-collector-contrib:ci-image-2
  RESTORE_CACHE_ATTEMPTS: 2
  BUILD_DD_REGISTRY: registry.ddbuild.io/ci/opentelemetry-collector-contrib
  BUILD_DEMO_REGISTRY: 172597598159.dkr.ecr.us-east-1.amazonaws.com/otel-collector-contrib
  BUILD_SANDBOX_REGISTRY: 601427279990.dkr.ecr.us-east-1.amazonaws.com/otel-collector-contrib
  DOCKERFILE: ci/Dockerfile
  # To use images from test-infra-definitions dev branches, set the SUFFIX variable to -dev
  # and check the job creating the image to make sure you have the right SHA prefix
  TEST_INFRA_DEFINITIONS_BUILDIMAGES_SUFFIX: ""
  # Make sure to update test-infra-definitions version in go.mod as well
  TEST_INFRA_DEFINITIONS_BUILDIMAGES: b02a714d7de7
stages:
  - manaul-jobs
  - e2e
  - build
  - push
  - staging-deploy
  - prod-deploy

# =======================================================================
# Build and deploy the images used for CI
# =======================================================================
.build-ci-image: &build-ci-image
  stage: build
  tags: ["runner:docker"]
  image: $CI_IMAGE
  script:
    - IMAGE_TAG_PREFIX=otelcolcontrib
    - TAG="$IMAGE_TAG_PREFIX-v$CI_COMMIT_SHORT_SHA"
    - docker build --file $DOCKERFILE --tag $BUILD_REGISTRY:$TAG --label target=staging .
    - docker push $BUILD_REGISTRY:$TAG
build-image-main:
  !!merge <<: *build-ci-image
  variables:
    BUILD_REGISTRY: $BUILD_DD_REGISTRY
.push-image: &push-image
  stage: push
  tags: ["runner:docker"]
  image: $CI_IMAGE
  dependencies:
    - build-image-main
  script:
    - IMAGE_TAG_PREFIX=otelcolcontrib
    - TAG="$IMAGE_TAG_PREFIX-v$CI_COMMIT_SHORT_SHA"
    - docker pull $BUILD_DD_REGISTRY:$TAG
    - docker tag $BUILD_DD_REGISTRY:$TAG $BUILD_REGISTRY:$TAG
    - docker push $BUILD_REGISTRY:$TAG
push-image-demo:
  !!merge <<: *push-image
  variables:
    BUILD_REGISTRY: $BUILD_DEMO_REGISTRY
    AWS_ACCT_ID: 172597598159
push-image-staging:
  !!merge <<: *push-image
  variables:
    BUILD_REGISTRY: $BUILD_SANDBOX_REGISTRY
    AWS_ACCT_ID: 601427279990

push-image-agent-qa:
  stage: push
  needs: ['build-image-main']
  trigger:
    project: DataDog/public-images
    branch: main
    strategy: depend
  variables:
    IMG_SOURCES: $BUILD_DD_REGISTRY:otelcolcontrib-v${CI_COMMIT_SHORT_SHA}
    IMG_DESTINATIONS: otel-collector-contrib:${CI_COMMIT_SHORT_SHA}
    IMG_REGISTRIES: agent-qa
  
build-ci-image:
  stage: manaul-jobs
  when: manual
  tags: ["runner:docker"]
  image: $CI_IMAGE
  script:
    - TAG=ci-image-2
    - docker build --file ci/Dockerfile.gitlab --tag $BUILD_DD_REGISTRY:$TAG .
    - docker push $BUILD_DD_REGISTRY:$TAG
.staging-deploy: &staging-deploy
  stage: staging-deploy
  tags: ["runner:docker", "size:large"]
  image: $CI_IMAGE
  dependencies:
    - push-image-staging
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /-staging$/'
  script:
    # # For debugging
    #- aws sts get-caller-identity
    - >-
      TEMP_AWS_ACCESS_KEY_ID=$(aws ssm get-parameter --region us-east-1 --name ci.opentelemetry-collector-contrib.sand-eks-deploy-api-key --with-decryption --query Parameter.Value --out text)
    - >-
      TEMP_AWS_SECRET_ACCESS_KEY=$(aws ssm get-parameter --region us-east-1 --name ci.opentelemetry-collector-contrib.sand-eks-deploy-access-key --with-decryption --query Parameter.Value --out text)
    - export AWS_ACCESS_KEY_ID=$TEMP_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$TEMP_AWS_SECRET_ACCESS_KEY
    # # For debugging
    # - aws sts get-caller-identity
    - bash $SCRIPT $NAMESPACE $VALUES
staging-deploy-demo-eks:
  !!merge <<: *staging-deploy
  variables:
    SCRIPT: ./ci/scripts/ci-deploy-staging.sh
    NAMESPACE: otel-staging
    VALUES: ./ci/values-staging.yaml
staging-deploy-gateway-eks:
  !!merge <<: *staging-deploy
  variables:
    SCRIPT: ./ci/scripts/ci-deploy-staging.sh
    NAMESPACE: otel-gateway
    VALUES: ./ci/values-gateway.yaml
staging-deploy-ds-gateway-eks:
  !!merge <<: *staging-deploy
  variables:
    SCRIPT: ./ci/scripts/ci-deploy-ds-gateway.sh
prod-deploy-demo-eks:
  stage: prod-deploy
  tags: ["runner:docker", "size:large"]
  image: $CI_IMAGE
  dependencies:
    - push-image-demo
  rules:
    - if: '$CI_COMMIT_REF_NAME == "prod"'
  script:
    # # For debugging
    #- aws sts get-caller-identity
    - >-
      TEMP_AWS_ACCESS_KEY_ID=$(aws ssm get-parameter --region us-east-1 --name ci.opentelemetry-collector-contrib.eks_access_key --with-decryption --query Parameter.Value --out text)
    - >-
      TEMP_AWS_SECRET_ACCESS_KEY=$(aws ssm get-parameter --region us-east-1 --name ci.opentelemetry-collector-contrib.eks_secret_access_key --with-decryption --query Parameter.Value --out text)
    - export AWS_ACCESS_KEY_ID=$TEMP_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$TEMP_AWS_SECRET_ACCESS_KEY
    # # For debugging
    # - aws sts get-caller-identity
    - bash ./ci/scripts/ci-deploy-demo.sh
.new_e2e_template:
  stage: e2e
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/test-infra-definitions/runner$TEST_INFRA_DEFINITIONS_BUILDIMAGES_SUFFIX:$TEST_INFRA_DEFINITIONS_BUILDIMAGES
  tags: ["arch:amd64"]
  before_script:
    # Setup AWS Credentials
    - mkdir -p ~/.aws
    - aws ssm get-parameter --region us-east-1 --name "ci.opentelemetry-collector-contrib.agent-qa-profile" --with-decryption --query "Parameter.Value" --output text >> ~/.aws/config
    - export AWS_PROFILE=agent-qa-ci
    # Now all `aws` commands target the agent-qa profile
    - aws ssm get-parameter --region us-east-1 --name "ci.opentelemetry-collector-contrib.ssh_public_key" --with-decryption --query "Parameter.Value" --output text > $E2E_PUBLIC_KEY_PATH
    - touch $E2E_PRIVATE_KEY_PATH && chmod 600 $E2E_PRIVATE_KEY_PATH && aws ssm get-parameter --region us-east-1 --name "ci.opentelemetry-collector-contrib.ssh_private_key" --with-decryption --query "Parameter.Value" --output text > $E2E_PRIVATE_KEY_PATH
    # Use S3 backend
    - pulumi login "s3://dd-pulumi-state?region=us-east-1&awssdk=v2&profile=$AWS_PROFILE"
  variables:
    KUBERNETES_MEMORY_REQUEST: 12Gi
    KUBERNETES_MEMORY_LIMIT: 16Gi
    KUBERNETES_CPU_REQUEST: 6
    E2E_PUBLIC_KEY_PATH: /tmp/agent-qa-ssh-key.pub
    E2E_PRIVATE_KEY_PATH: /tmp/agent-qa-ssh-key
    E2E_KEY_PAIR_NAME: ci.open-elemetry-collector-contrib
    E2E_OUTPUT_DIR: $CI_PROJECT_DIR/e2e-output
  script:
    - cd e2e-tests && go test $TARGETS/... -v timeout 0

# new-e2e-otel-collector:
#   extends: .new_e2e_template
#   variables:
#     TARGETS: ./
#     TEAM: otel

