// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("docker_attributes")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/processor/dockerattributesprocessor"
)

const (
	TracesStability   = component.StabilityLevelDevelopment
	MetricsStability  = component.StabilityLevelDevelopment
	LogsStability     = component.StabilityLevelDevelopment
	ProfilesStability = component.StabilityLevelDevelopment
)
