receivers:
  otlp:
    protocols:
      http:
        endpoint: "localhost:4318"
      grpc:
        endpoint: "localhost:4317"

processors:
  batch:
    send_batch_max_size: 1000
    send_batch_size: 100
    timeout: 10s

exporters:
  # Datadog exporter with routing configuration
  datadog:
    api:
      site: ${env:DD_SITE}
      key: ${env:DD_API_KEY}
    
    # Metrics routing configuration
    metrics:
      routing:
        enabled: true
        otlp_endpoint: "https://trace.agent.${DD_SITE}/api/v0.2/stats" # replace "${DD_SITE}" with your Datadog site manually
        otlp_headers:
          "Dd-Protocol": "otlp"
          "X-Datadog-Reported-Languages": "java"
        rules:
          - name: "datadog_trace_metrics"
            condition:
              instrumentation_scope_name: "datadog.trace.metrics"
            target: "otlp"
          - name: "special_service_metrics"
            condition:
              resource_attributes:
                "service.name": "special-service"
            target: "otlp"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog] 