nodeSelector:
  alpha.eksctl.io/nodegroup-name: ng-6
clusterRole:
  name: "opentelemetry-collector-ds"
  clusterRoleBinding:
    name: opentelemetry-collector-ds
config:
  exporters:
    otlp:
      endpoint: opentelemetry-collector.otel-ds-gateway.svc.cluster.local:4317
      tls:
        insecure: true
  processors:
    k8sattributes:
      passthrough: false
      auth_type: "serviceAccount"
  service:
    pipelines:
      metrics:
        receivers: [otlp]
        processors: [k8sattributes, batch]
        exporters: [datadog]
      traces:
        receivers: [otlp]
        processors: [k8sattributes, batch]
        exporters: [otlp]
      traces/sampled:
        receivers: []
        processors: []
        exporters: []
      logs:
        processors: [k8sattributes, batch]
        exporters: [otlp]
resources:
  limits:
    # necessary to decrease memory from 2 to 1 Gi in order to
    # have sufficient memory to schedule all pods on Nodes.
    memory: 1Gi
