nodeSelector:
  alpha.eksctl.io/nodegroup-name: ng-3
presets:
  logsCollection:
    enabled: false
config:
  processors:
    batch:
      send_batch_max_size: 100
      send_batch_size: 10
      timeout: 10s