mode: deployment
replicaCount: 3
nodeSelector:
  alpha.eksctl.io/nodegroup-name: ng-5
clusterRole:
  name: "opentelemetry-collector-gateway"
  clusterRoleBinding:
    name: opentelemetry-collector-gateway
presets:
  logsCollection:
    enabled: true
