nodeSelector:
  alpha.eksctl.io/nodegroup-name: ng-6
clusterRole:
  name: "opentelemetry-collector-ds"
  clusterRoleBinding:
    name: opentelemetry-collector-ds
config:
  exporters:
    otlp:
      endpoint: opentelemetry-collector:4317
      tls:
        insecure: true
  service:
    pipelines:
      metrics:
        exporters: [otlp]
      traces:
        exporters: [datadog/connector]
      traces/sampled:
        exporters: [otlp, debug]
      logs:
        exporters: [otlp]
resources:
  limits:
    # necessary to decrease memory from 2 to 1 Gi in order to
    # have sufficient memory to schedule all pods on Nodes.
    memory: 1Gi
