nodeSelector:
  alpha.eksctl.io/nodegroup-name: ng-6
clusterRole:
  name: "opentelemetry-collector-ds"
  clusterRoleBinding:
    name: opentelemetry-collector-ds
config:
  exporters:
    otlp:
      endpoint: opentelemetry-collector.otel-ds-gateway.svc.cluster.local:4317
      tls:
        insecure: true
  processors:
    k8sattributes:
      passthrough: true
      auth_type: "serviceAccount"
  receivers:
    otlp/2:
      protocols:
        grpc:
          endpoint: 0.0.0.0:1234
  service:
    pipelines:
      metrics:
        receivers: [otlp]
        processors: [k8sattributes, batch]
        exporters: [otlp]
      traces:
        receivers: [otlp]
        processors: [k8sattributes, batch]
        exporters: [otlp]
      # hack to disable this pipeline. otlp/2 does not receive data.
      traces/sampled:
        receivers: [otlp/2]
        processors: []
        exporters: [otlp]
      logs:
        processors: [k8sattributes, batch]
        exporters: [otlp]
resources:
  limits:
    # necessary to decrease memory from 2 to 1 Gi in order to
    # have sufficient memory to schedule all pods on Nodes.
    memory: 1Gi
