mode: deployment
replicaCount: 3
nodeSelector:
  alpha.eksctl.io/nodegroup-name: ng-5
clusterRole:
  name: "opentelemetry-collector-gateway"
  clusterRoleBinding:
    name: opentelemetry-collector-gateway
presets:
  logsCollection:
    enabled: false
resources:
  limits:
    cpu: 800m
    memory: 4Gi
  requests:
    cpu: 512m
    memory: 2Gi
config:
  processors:
    batch:
      send_batch_max_size: 100
      send_batch_size: 10
      timeout: 10s
